### ISSUE TITLE
group feature 

### ISSUE THREAD

**Issue by paul45** [michalsn/codeigniter-tags#4]
thx for this module 

What do you think about add un group feature 
if several tables do not have the same tags you can render only tags for this table

**Comment by michalsn** [comment]
I don't think I understand what you mean. Can you please elaborate more, maybe with an example?

**Comment by paul45** [comment]
add a column 'group' in tags table 
allow to set group when insert or save tags
```
insert(
    'tags'   => 'tag1,tag2,tag3',
    'groups'   => 'group1,group2,group3',
])
```
allow to select only one group in TagModel

`model(TagModel::class)->where('group','group1')->find()`

use case : 
i have three taggable model (ImageModel ,EventModel, NewsModel)
i want allow tags (landscape,portait,drawing..) for ImageModel
and  allow tags (meeting,vacation...) for EventModel
i don't want landscape,portait,drawing tags in suggestions on EventModel
i don't want meeting,vacation tags in suggestions on ImageModel
i want all tags in suggestions on NewsModel

**Comment by michalsn** [comment]
Hmm... I can add a method to grab tags for certain models (tables), but I don't think I want to go any further.

Allowing/disallowing tags to be selected is a task for validation.

Also, right now, we are cleaning up the tags that are no longer used: https://github.com/michalsn/codeigniter-tags/blob/develop/src/Models/TagModel.php#L70, so if you want to add tags before they are used, then it will not work well.

**Comment by paul45** [comment]
> Also, right now, we are cleaning up the tags that are no longer used: https://github.com/michalsn/codeigniter-tags/blob/develop/src/Models/TagModel.php#L70, so if you want to add tags before they are used, then it will not work well.

ok i didn't understand that

**Comment by michalsn** [comment]
When you update an entry that has tags, the library will search for unused tags and delete them.

Example:
```php
// this code will produce 3 entries in the tags table
$id = model(ImageModel::class)->insert([
    'name' => 'sampleFile.jpeg',
    'tags' => 'tag1,tag2,tag3',
]);
// this code will reduce entries in the tags table to 1
model(ImageModel::class)->save([
    'id'   => $id,
    'tags' => 'tag1',
]);
```

In other words, you cannot have tags in the `tags` table that are not used anywhere (by other models).

I assumed that you want to pre-add tags and then limit their use in some models.

**Comment by paul45** [comment]
ok i understand

**Comment by michalsn** [comment]
Please, let me know if that will help you in any way: #6
